name: crice_hospital_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked_services:
  stacked:
#  im_stepper: ^0.1.3
#  steps: ^1.0.1
  flutter_svg: ^0.21.0+1
  #General
  intl: ^0.17.0
  injectable: ^1.2.2
#  injectable_generator: ^1.1.2
  get_it: ^6.0.0
#  buildRunner
  build_runner: ^1.10.0
  #router
  auto_route:
  auto_route_generator:
  json_annotation: 3.1.1
#  json_serializable: 3.5.1
  #imagePicker
#  image_picker: ^0.6.6+4
  #http
  http:
  dio:
  path_provider: ^2.0.1
  fluttertoast:
  shared_preferences: ^2.0.5
  flutter_html:
  #FilePdf
#  flutter_downloader: ^1.6.0
#  multi_downloader: ^1.0.6
#  permission_handler: ^7.1.0
  ext_storage: ^1.0.3
  date_format: ^2.0.2
  basic_utils: ^1.4.0
  flutter_webview_plugin: ^0.3.11
  permission_handler: '^4.4.0+hotfix.1'
  # flutter_web_view: ^0.0.6
  # webview_flutter: ^2.0.4
#  flutter_inappwebview: ^5.3.2
  youtube_player_flutter: ^8.0.0
  jiffy: ^4.1.0
  date_range_picker: ^1.0.7
  progress_dialog:
  open_file:
  webview_flutter: ^2.0.8
#  zoom_widget: ^0.1.3
  pinch_zoom: ^0.1.0-nullsafety.0
  firebase_core:
  flutter_local_notifications:
  firebase_messaging:
  firebase_crashlytics: ^0.4.0+1
  lazy_load_scrollview: ^1.3.0
  get: ^4.1.4



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher-logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
       - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 700
#           style: Regular
#     - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
